# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# The site title
title: 睿

# The Disqus shortname; Unless you don't want to enable the comments system, you must specify this parameter. It is used in the production environment.
# disqus: raysworld2013  

# The Google Analytics tracking ID; It is used in the production environment.
# google_analytics: 

# The name of the author of the site; It would be showed in the copyright statement.
author: Rui LI
# The avatar of the author of the site.
avatar: "/img/avatar-icon.jpg"
# The email of the author of the site.
email: raysworld[AT]outlook.com 
# The current living location of the author of the site.
location: Chongqing, China
# The number of posts on each page.
# paginate: 10


description: >- # this means to ignore newlines until "baseurl:"
  上善若水，厚德载物.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://raysworld.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# # Sidebar settings
# navbar-links:
#   About Me: "about"
#   Links:
#     - CQU: "http://accu.cqu.edu.cn/ywb/HOME.htm"
#     - TUM@I6: "https://www.in.tum.de/i06/home/"
#   Author's home: "http://raysworld.github.io"


# social-network-links:
#   email: "raysworld[AT]outlook.com"
#   rss: true  # remove this line if you don't want to show an RSS link at the bottom
#   github: raysworld
#   linkedin: 睿-李-406922b1
#   ORCID: 0000-0002-8877-8524
#   google-scholar: citations?user=2UqidQYAAAAJ


# Build settings
markdown: kramdown
highlighter: rouge
# theme: jekyll-theme-hamilton
remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  - jekyll-remote-theme
  # - jekyll-feed
  # - jekyll-paginate
  # - jekyll-sitemap

kramdown:
  input: GFM

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: ae5614a5d29a1e4236ae                            #生成的clientID
  clientSecret: cd324fc19b51821eb6ab4eeead85fda62b3fc8a3    #生成的clientSecret
  repo: raysworld.github.io    #仓库名称
  owner: raysworld    #github用户名
  admin: raysworld
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
